extends Node

enum DomeTypeEnum {
	HOUSING, INDUSTRIAL, MINING, LIFE_SUPPORT, LUXURY, RESEARCH, SPACE_ELEVATOR, WORMHOLE, CONTROL_CENTER
}
enum DomeCorpsEnum { CORP1, CORP2, CORP3, CORP4, CORP5 }
enum DomeStatusEnum { IDLE, PRODUCING, STRIKE, COLLAPSED, BUILDING }

# TODO: Add more laws here
enum LawsEnum {
	RATIONING,
	PRESERVE,
	EXPAND_HABITATION,
	WORK_MORE,
	ROUND_THE_CLOCK,
	STOCKPILE_OVERSEER,
	CORPORATE_SUBSIDIES,
}
