extends Node

enum DomeTypeEnum {
	HOUSING, INDUSTRIAL, MINING, LIFE_SUPPORT, LUXURY, RESEARCH, SPACE_ELEVATOR, WORMHOLE, CONTROL_CENTER
}
enum DomeCorpsEnum { CORP1, CORP2, CORP3, CORP4, CORP5 }
enum DomeStatusEnum { IDLE, PRODUCING, STRIKE, COLLAPSED, BUILDING }

# TODO: Add more laws here
enum LawsEnum {
	RATIONING,
	PRESERVE,
	EXPAND_HABITATION,
	WORK_MORE,
	ROUND_THE_CLOCK,
	STOCKPILE_OVERSEER,
	CORPORATE_SUBSIDIES,
}

enum TaskAffiliation { EARTH, MARS, CORP1, CORP2, CORP3, CORP4, CORP5 }
enum Task {
	NONE,
	E_STOCKPILE_500_LIFE_SUPPORT,
	E_STOCKPILE_500_ALLOYS,
	E_INCOME_100_MINERALS,
	E_INCOME_50_LIFE_SUPPORT_50_ALLOYS,
	E_BUILD_2_DOMES,
	E_REPAIR_DOMES,
}
